// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZx9sd-dSUNhqWP5YjWyPSOF6jQB6X8Ak',
    appId: '1:203251492751:web:4742ad2976c9de4ba04dfa',
    messagingSenderId: '203251492751',
    projectId: 'waiterbar-3208a',
    authDomain: 'waiterbar-3208a.firebaseapp.com',
    storageBucket: 'waiterbar-3208a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw45tDANuO1vGo13wejjdF7zOf-w5PxgM',
    appId: '1:203251492751:android:9e559f721402992ba04dfa',
    messagingSenderId: '203251492751',
    projectId: 'waiterbar-3208a',
    storageBucket: 'waiterbar-3208a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqmoRl9pMiFfbXaD_1FEGM7qxG72n09ik',
    appId: '1:203251492751:ios:bccbdab7fdf269a3a04dfa',
    messagingSenderId: '203251492751',
    projectId: 'waiterbar-3208a',
    storageBucket: 'waiterbar-3208a.appspot.com',
    iosClientId: '203251492751-c10ttd39o6mdls509l2d0qhqvo628csh.apps.googleusercontent.com',
    iosBundleId: 'com.example.waiterbar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqmoRl9pMiFfbXaD_1FEGM7qxG72n09ik',
    appId: '1:203251492751:ios:37811c810ab4b0a0a04dfa',
    messagingSenderId: '203251492751',
    projectId: 'waiterbar-3208a',
    storageBucket: 'waiterbar-3208a.appspot.com',
    iosClientId: '203251492751-oedhmhanv4qcst7bbnkuok1rnj6t3gvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.waiterbar.RunnerTests',
  );
}
